In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("loan_prediction.csv")
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [3]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [5]:
data["LoanAmount"] = data["LoanAmount"].fillna(data["LoanAmount"].mean())
data["LoanAmount"].isnull().sum()

0

In [6]:
data["Loan_Amount_Term"] = data["Loan_Amount_Term"].fillna(data["Loan_Amount_Term"].mean())
data["Loan_Amount_Term"].isnull().sum()

0

In [7]:
data["Credit_History"] = data["Credit_History"].fillna(data["Credit_History"].mean())
data["Credit_History"].isnull().sum()

0

In [8]:
data["Gender"] = data["Gender"].fillna(method = "ffill")
data["Gender"].isnull().sum()

0

In [9]:
data["Married"] = data["Married"].fillna(method = "ffill")
data["Dependents"] = data["Dependents"].fillna(method = "ffill")
data["Self_Employed"] = data["Self_Employed"].fillna(method = "ffill")

In [10]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
data = data.drop(columns = "Loan_ID")
data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
data["Gender"] = le.fit_transform(data["Gender"])
data["Married"] = le.fit_transform(data["Married"])
data["Education"] = le.fit_transform(data["Education"])
data["Self_Employed"] = le.fit_transform(data["Self_Employed"])
data["Loan_Status"] = le.fit_transform(data["Loan_Status"])
data["Dependents"] = le.fit_transform(data["Dependents"])
data["Property_Area"] = le.fit_transform(data["Property_Area"])

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int32
 1   Married            614 non-null    int32
 2   Dependents         614 non-null    int32
 3   Education          614 non-null    int32
 4   Self_Employed      614 non-null    int32
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    int32
 11  Loan_Status        614 non-null    int32
dtypes: float64(4), int32(7), int64(1)
memory usage: 40.9 KB

In [16]:
x = data.drop(columns = "Loan_Status")
x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,0,0,5849,0.0,146.412162,360.0,1.0,2
1,1,1,1,0,0,4583,1508.0,128.000000,360.0,1.0,0
2,1,1,0,0,1,3000,0.0,66.000000,360.0,1.0,2
3,1,1,0,1,0,2583,2358.0,120.000000,360.0,1.0,2
4,1,0,0,0,0,6000,0.0,141.000000,360.0,1.0,2

In [17]:
y = data.Loan_Status
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int32

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scale = StandardScaler()

In [20]:
x_scaled = pd.DataFrame(scale.fit_transform(x))
x_scaled

,0,1,2,3,4,5,6,7,8,9,10
0,0.477493,-1.367172,-0.752177,-0.528362,-0.403582,0.072991,-0.554487,0.000000,0.279851,0.451640,1.223298
1,0.477493,0.731437,0.236767,-0.528362,-0.403582,-0.134412,-0.038732,-0.219273,0.279851,0.451640,-1.318513
2,0.477493,0.731437,-0.752177,-0.528362,2.477808,-0.393747,-0.554487,-0.957641,0.279851,0.451640,1.223298
3,0.477493,0.731437,-0.752177,1.892641,-0.403582,-0.462062,0.251980,-0.314547,0.279851,0.451640,1.223298
4,0.477493,-1.367172,-0.752177,-0.528362,-0.403582,0.097728,-0.554487,-0.064454,0.279851,0.451640,1.223298
...,...,...,...,...,...,...,...,...,...,...,...
609,-2.094270,-1.367172,-0.752177,-0.528362,-0.403582,-0.410130,-0.554487,-0.898095,0.279851,0.451640,-1.318513
610,0.477493,0.731437,2.214653,-0.528362,-0.403582,-0.212557,-0.554487,-1.267279,-2.518655,0.451640,-1.318513
611,0.477493,0.731437,0.236767,-0.528362,-0.403582,0.437174,-0.472404,1.269371,0.279851,0.451640,1.223298
612,0.477493,0.731437,1.225710,-0.528362,-0.403582,0.357064,-0.554487,0.483367,0.279851,0.451640,1.223298
613,-2.094270,-1.367172,-0.752177,-0.528362,2.477808,-0.134412,-0.554487,-0.159728,0.279851,-2.410441,-0.047607

In [21]:
from sklearn.model_selection import train_test_split

In [101]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size = 0.2,random_state = 3)  # 3

In [102]:
from sklearn.tree import DecisionTreeClassifier

In [120]:
dtr = DecisionTreeClassifier(criterion = "entropy",random_state = )

In [121]:
dtr.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=3)

In [122]:
pred = dtr.predict(x_test)

In [123]:
pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [124]:
y_test

455    1
132    1
244    1
53     0
264    1
      ..
544    1
129    0
360    0
446    1
321    1
Name: Loan_Status, Length: 123, dtype: int32

In [125]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [126]:
accuracy=accuracy_score(y_test,pred)
conmat=confusion_matrix(y_test,pred)

In [127]:
print(accuracy)
print(conmat)

0.7560975609756098
[[16 12]
 [18 77]]